// DO NOT EDIT. generated by github.com/tinywasm/orm

package workschedule

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *Staff) ModelName() string {
	return "staff"
}

var _schemaStaff = []fmt.Field{
		{Name: "id", Type: fmt.FieldInt, DB: &fmt.FieldDB{PK: true}},
		{Name: "name", Type: fmt.FieldText, NotNull: true},
		{Name: "role", Type: fmt.FieldText, NotNull: true},
		{Name: "email", Type: fmt.FieldText, DB: &fmt.FieldDB{Unique: true}},
	}

func (m *Staff) Schema() []fmt.Field { return _schemaStaff }

func (m *Staff) Pointers() []any {
	return []any{
		&m.ID,
		&m.Name,
		&m.Role,
		&m.Email,
	}
}

func (m *Staff) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var Staff_ = struct {
	ModelName string
	ID string
	Name string
	Role string
	Email string
}{
	ModelName: "staff",
	ID: "id",
	Name: "name",
	Role: "role",
	Email: "email",
}

func ReadOneStaff(qb *orm.QB, model *Staff) (*Staff, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllStaff(qb *orm.QB) ([]*Staff, error) {
	var results []*Staff
	err := qb.ReadAll(
		func() fmt.Model { return &Staff{} },
		func(m fmt.Model) { results = append(results, m.(*Staff)) },
	)
	return results, err
}

func (m *WorkCalendar) ModelName() string {
	return "workcalendar"
}

var _schemaWorkCalendar = []fmt.Field{
		{Name: "id", Type: fmt.FieldInt, DB: &fmt.FieldDB{PK: true}},
		{Name: "staff_id", Type: fmt.FieldInt, NotNull: true},
		{Name: "day_of_week", Type: fmt.FieldInt, NotNull: true},
		{Name: "start_time", Type: fmt.FieldText, NotNull: true},
		{Name: "end_time", Type: fmt.FieldText, NotNull: true},
		{Name: "is_active", Type: fmt.FieldBool, NotNull: true},
	}

func (m *WorkCalendar) Schema() []fmt.Field { return _schemaWorkCalendar }

func (m *WorkCalendar) Pointers() []any {
	return []any{
		&m.ID,
		&m.StaffID,
		&m.DayOfWeek,
		&m.StartTime,
		&m.EndTime,
		&m.IsActive,
	}
}

func (m *WorkCalendar) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var WorkCalendar_ = struct {
	ModelName string
	ID string
	StaffID string
	DayOfWeek string
	StartTime string
	EndTime string
	IsActive string
}{
	ModelName: "workcalendar",
	ID: "id",
	StaffID: "staff_id",
	DayOfWeek: "day_of_week",
	StartTime: "start_time",
	EndTime: "end_time",
	IsActive: "is_active",
}

func ReadOneWorkCalendar(qb *orm.QB, model *WorkCalendar) (*WorkCalendar, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWorkCalendar(qb *orm.QB) ([]*WorkCalendar, error) {
	var results []*WorkCalendar
	err := qb.ReadAll(
		func() fmt.Model { return &WorkCalendar{} },
		func(m fmt.Model) { results = append(results, m.(*WorkCalendar)) },
	)
	return results, err
}
