// Code generated by ormc; DO NOT EDIT.
// NOTE: Schema() and Values() must always be in the same field order.
// String PK: set via github.com/tinywasm/unixid before calling db.Create().
package workschedule

import (
	"github.com/tinywasm/orm"
)

func (m *Staff) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeInt64, Constraints: orm.ConstraintPK},
		{Name: "name", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "role", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "email", Type: orm.TypeText, Constraints: orm.ConstraintUnique},
	}
}

func (m *Staff) Values() []any {
	return []any{
		m.ID,
		m.Name,
		m.Role,
		m.Email,
	}
}

func (m *Staff) Pointers() []any {
	return []any{
		&m.ID,
		&m.Name,
		&m.Role,
		&m.Email,
	}
}

var StaffMeta = struct {
	TableName string
	ID string
	Name string
	Role string
	Email string
}{
	TableName: "staff",
	ID: "id",
	Name: "name",
	Role: "role",
	Email: "email",
}

func ReadOneStaff(qb *orm.QB, model *Staff) (*Staff, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllStaff(qb *orm.QB) ([]*Staff, error) {
	var results []*Staff
	err := qb.ReadAll(
		func() orm.Model { return &Staff{} },
		func(m orm.Model) { results = append(results, m.(*Staff)) },
	)
	return results, err
}

func (m *WorkCalendar) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeInt64, Constraints: orm.ConstraintPK},
		{Name: "staff_id", Type: orm.TypeInt64, Constraints: orm.ConstraintNotNull, Ref: "staff"},
		{Name: "day_of_week", Type: orm.TypeInt64, Constraints: orm.ConstraintNotNull},
		{Name: "start_time", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "end_time", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "is_active", Type: orm.TypeBool, Constraints: orm.ConstraintNotNull},
	}
}

func (m *WorkCalendar) Values() []any {
	return []any{
		m.ID,
		m.StaffID,
		m.DayOfWeek,
		m.StartTime,
		m.EndTime,
		m.IsActive,
	}
}

func (m *WorkCalendar) Pointers() []any {
	return []any{
		&m.ID,
		&m.StaffID,
		&m.DayOfWeek,
		&m.StartTime,
		&m.EndTime,
		&m.IsActive,
	}
}

var WorkCalendarMeta = struct {
	TableName string
	ID string
	StaffID string
	DayOfWeek string
	StartTime string
	EndTime string
	IsActive string
}{
	TableName: "workcalendar",
	ID: "id",
	StaffID: "staff_id",
	DayOfWeek: "day_of_week",
	StartTime: "start_time",
	EndTime: "end_time",
	IsActive: "is_active",
}

func ReadOneWorkCalendar(qb *orm.QB, model *WorkCalendar) (*WorkCalendar, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWorkCalendar(qb *orm.QB) ([]*WorkCalendar, error) {
	var results []*WorkCalendar
	err := qb.ReadAll(
		func() orm.Model { return &WorkCalendar{} },
		func(m orm.Model) { results = append(results, m.(*WorkCalendar)) },
	)
	return results, err
}
